/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Tue Jul  3 16:15:50 2018"
#define BUILD_TIME (1530648950UL)

#define VERSION_NUMBER 0x03060200UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c517dUL
#define VERSION_SANITY2 0x148c24958UL
#define VERSION_SANITY3 0x00028000UL

#define VERSION_STRING "3.6.2-0"
#define VERSION_ID \
 "MacOSX NetHack Version 3.6.2-0 Beta - last build Tue Jul  3 16:15:50 2018."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.2-0 MacOSX Beta, built Jul  3 16:15:50 2018."

#define NETHACK_GIT_SHA "4b98266e2562f2b803d320b96502f26303d9583c"
#define NETHACK_GIT_BRANCH "NetHack-3.6.0"
