/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sat Feb 10 22:08:36 2018"
#define BUILD_TIME (1518318516UL)

#define VERSION_NUMBER 0x03060100UL
#define VERSION_FEATURES 0x00060000UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c517dUL
#define VERSION_SANITY2 0x148c24958UL
#define VERSION_SANITY3 0x00028000UL

#define VERSION_STRING "3.6.1-0"
#define VERSION_ID \
 "MacOSX NetHack Beta Version 3.6.1-0 - last build Sat Feb 10 22:08:36 2018."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.1-0 MacOSX Beta, built Feb 10 22:08:36 2018."

